[package]
name = "rust_lib_keepass_one"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
anyhow = "1.0.98"
thiserror = "2.0.12"
byteorder = "1.5.0"
hex-literal = "1.0.0"
xml = "1.0.0"
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
hex = "0.4.3"
base64 = "0.22.1"
sha2 = "0.10.9"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
