// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open a KDBX key file and return the key
Uint8List openKdbxKeyFile({required List<int> keyFile}) =>
    RustLib.instance.api.crateApiKdbxOpenKdbxKeyFile(keyFile: keyFile);
